//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_Recyclebin
    {
        public string Recyclebin_ID { get; set; }
        public string Recyclebin_Name { get; set; }
        public string Recyclebin_Database { get; set; }
        public string Recyclebin_Table { get; set; }
        public string Recyclebin_FieldKey { get; set; }
        public string Recyclebin_EventField { get; set; }
        public string Recyclebin_Remark { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
    }
}
