//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Base_UserInfo()
        {
            this.Base_O_A_Setup = new HashSet<Base_O_A_Setup>();
            this.Base_StaffOrganize = new HashSet<Base_StaffOrganize>();
            this.Base_UserInfoUserGroup = new HashSet<Base_UserInfoUserGroup>();
            this.Base_UserRight = new HashSet<Base_UserRight>();
            this.Base_UserRole = new HashSet<Base_UserRole>();
        }
    
        public string User_ID { get; set; }
        public string User_Code { get; set; }
        public string User_Account { get; set; }
        public string User_Pwd { get; set; }
        public string User_Name { get; set; }
        public Nullable<int> User_Sex { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string Theme { get; set; }
        public string Question { get; set; }
        public string AnswerQuestion { get; set; }
        public Nullable<int> DeleteMark { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUserId { get; set; }
        public string ModifyUserName { get; set; }
        public string User_Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Base_O_A_Setup> Base_O_A_Setup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Base_StaffOrganize> Base_StaffOrganize { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Base_UserInfoUserGroup> Base_UserInfoUserGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Base_UserRight> Base_UserRight { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Base_UserRole> Base_UserRole { get; set; }
    }
}
